version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "dotnet ef database update --no-build && dotnet Chat.dll"
    depends_on:
      - sqlserver
      - migration
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  client:
    build:
      context: ./chat-client
      dockerfile: ./Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ./chat-client/dist:/usr/share/nginx/html
    depends_on:
      - app

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "DevelpmentP@ssword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      - sqlserver

volumes:
  sqlserver-data: