version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "dotnet ef database update --no-build && dotnet Chat.dll"
    depends_on:
      - sqlserver
      - migration
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - api-network
      - database-network

  client:
    build:
      context: ./chat-client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - VITE_APP_MODE=development
      - VITE_APP_PORT=3000
      - NODE_ENV=development
    volumes:
      - ./chat-client:/app
      - /app/node_modules
    depends_on:
      - app
    networks:
      - api-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "DevelpmentP@ssword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - database-network

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      - sqlserver
    networks:
      - database-network

volumes:
  sqlserver-data:

networks:
  api-network:
    driver: bridge
  database-network:
    driver: bridge